# Generated by Django 3.1.7 on 2021-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210503_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_gender',
            field=models.CharField(choices=[(None, 'No Gender'), ('male', 'Male'), ('female', 'Female')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_side',
            field=models.CharField(choices=[(None, 'No Side'), ('right', 'Right-Handed'), ('left', 'Left-Handed')], default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.CharField(choices=[(None, 'No Side'), ('jr', 'Junior'), ('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large')], default=None, max_length=2),
        ),
    ]
