# Generated by Django 3.1.7 on 2021-05-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210504_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_gender',
            field=models.CharField(blank=True, choices=[(None, 'No Gender'), ('male', 'Male'), ('female', 'Female')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_side',
            field=models.CharField(blank=True, choices=[(None, 'No Side'), ('right', 'Right-Handed'), ('left', 'Left-Handed')], default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.CharField(blank=True, choices=[(None, 'No Side'), ('jr', 'Junior'), ('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large')], default=None, max_length=2, null=True),
        ),
    ]
